# Site settings
title: Blog 
description: "A minimal blog, build with Jekyll."
url: "https://mehra-deepak.github.io/blog/"
author:
  name: "Deepak Mehra"
  email: "work.mehradeepak@gmail.com"
  url: "https://mehra-deepak.github.io/blog/"

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
